security:
    acl:
        connection: default

    role_hierarchy:
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                    dddp:  { password: dddp, roles: [ 'ROLE_USER' ] }
                    moderator:  { password: moderator, roles: [ 'ROLE_MODERATOR' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { password: superadmin, roles: [ 'ROLE_SUPER_ADMIN' ] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:

        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider:  in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_REMEMBERED }

