computer:
    path:     /
    defaults: { _controller: "ParkBundle:Computer:index" }

computer_debug:
    path:     /debug
    defaults: { _controller: "ParkBundle:Computer:debug" }

computer_test:
    path:     /test
    defaults: { _controller: ParkBundle:Computer:test }
